### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by matinas** [matinas/shadersfromscratch#1]
![1 emissionalbedo](https://user-images.githubusercontent.com/5633645/39080208-817b7c34-4500-11e8-8ec5-a52781e1629c.png)
![2 emissionalbedonormal](https://user-images.githubusercontent.com/5633645/39080209-81af5108-4500-11e8-9c7a-8fd69307f7d7.png)
![3 skyboxreflection](https://user-images.githubusercontent.com/5633645/39080210-81cf413e-4500-11e8-936a-fd7ea015627b.png)
![5 fullgreen](https://user-images.githubusercontent.com/5633645/39080211-81f2393c-4500-11e8-84c1-a497c784b39b.png)
![7 emissionalbedotexture](https://user-images.githubusercontent.com/5633645/39080212-821279fe-4500-11e8-8de3-68ba3ba71fea.png)
![8 diffusenormal](https://user-images.githubusercontent.com/5633645/39080213-82337834-4500-11e8-88a3-3e21be1d2538.png)
![9 diffusenormalintensity](https://user-images.githubusercontent.com/5633645/39080215-825458e2-4500-11e8-9d4f-c154092260bc.png)
![11 snow](https://user-images.githubusercontent.com/5633645/39080216-8275e49e-4500-11e8-8e0d-d14c0c54b4c3.png)
![14 normalscaler](https://user-images.githubusercontent.com/5633645/39080218-82998d9a-4500-11e8-9f7a-f7c01611d81e.png)
![15 normalvisualizer](https://user-images.githubusercontent.com/5633645/39080219-82bb6294-4500-11e8-8d5c-5cb87cd492b5.png)
![17 metallicreflectivebump](https://user-images.githubusercontent.com/5633645/39080220-82dbaf54-4500-11e8-92f2-841911d0aba6.png)
![18 dotproductalbedo](https://user-images.githubusercontent.com/5633645/39080221-82fc3850-4500-11e8-8f73-3e751c6e7078.png)
![19 rim](https://user-images.githubusercontent.com/5633645/39080222-831c59a0-4500-11e8-9346-68f0aa17d44d.png)
![21 rimbands](https://user-images.githubusercontent.com/5633645/39080223-833cefd0-4500-11e8-8efe-ef562bc7ce02.png)
![22 stripes](https://user-images.githubusercontent.com/5633645/39080224-8360cbee-4500-11e8-96ac-1529cf8d132e.png)
![23 stripedrim](https://user-images.githubusercontent.com/5633645/39080225-83994500-4500-11e8-83f6-b9cabf925383.png)
![24 texturedstripedrim](https://user-images.githubusercontent.com/5633645/39080226-83bdc07e-4500-11e8-8520-8a8e097501fa.png)
![25 basicblinnphong](https://user-images.githubusercontent.com/5633645/39080227-83f061d2-4500-11e8-8dda-5495bdd41cf0.png)
![26 pbrmetallic](https://user-images.githubusercontent.com/5633645/39080228-842dcfa4-4500-11e8-9e3b-c689d4e9f840.png)
![27 pbrspecular](https://user-images.githubusercontent.com/5633645/39080229-844ea17a-4500-11e8-8c6f-923bfb1cc7e7.png)
![28 pbrspecularemission](https://user-images.githubusercontent.com/5633645/39080230-846ef826-4500-11e8-8dac-83184b85489a.png)
![29 pbrspecularreversedmap](https://user-images.githubusercontent.com/5633645/39080231-848fff26-4500-11e8-9468-704a55a8391c.png)
![30 lightingsimplelambert](https://user-images.githubusercontent.com/5633645/39080232-84b0cd32-4500-11e8-9e79-78744d8c8864.png)
![31 lightingsimpleblinnphong](https://user-images.githubusercontent.com/5633645/39080233-84d1ef26-4500-11e8-9bd3-deeca158a5d1.png)
![33 lightingtoonalbedo](https://user-images.githubusercontent.com/5633645/39080234-84f680ac-4500-11e8-904e-4abfd5b017e8.png)
![34 lightingtoonspecular](https://user-images.githubusercontent.com/5633645/39080235-851735b8-4500-11e8-8a0f-c20617e6982b.png)
![36 simplealpha](https://user-images.githubusercontent.com/5633645/39080236-853846ea-4500-11e8-9ef2-3a33b14ba7bf.png)
![37 hardrimhologram](https://user-images.githubusercontent.com/5633645/39080237-85584d14-4500-11e8-9bb9-724cb321aac0.png)
![40 decal](https://user-images.githubusercontent.com/5633645/39080238-8578fe56-4500-11e8-8208-9e63346f680c.png)
![42 decalovertex](https://user-images.githubusercontent.com/5633645/39080239-8599b268-4500-11e8-81de-fe0c762f2633.png)
![48 screengrabvf](https://user-images.githubusercontent.com/5633645/39080240-85ba5202-4500-11e8-8589-4cca4b43a1dc.png)
![49 diffusevf](https://user-images.githubusercontent.com/5633645/39080241-85de2c68-4500-11e8-8d47-8d5529558a3c.png)
![50 diffusevfshadowcasting](https://user-images.githubusercontent.com/5633645/39080242-8600c124-4500-11e8-8a32-4b7f1463438e.png)
![51 diffusevfshadowreceiving](https://user-images.githubusercontent.com/5633645/39080243-8621a1e6-4500-11e8-97d9-424dde279c53.png)
![52 normalextrusion](https://user-images.githubusercontent.com/5633645/39080244-8642ef5e-4500-11e8-8539-d6b0f27a070b.png)
![53 simpleoutline](https://user-images.githubusercontent.com/5633645/39080245-8662c6e4-4500-11e8-9154-883c5716700c.png)
![54 advancedoutline](https://user-images.githubusercontent.com/5633645/39080246-86840480-4500-11e8-9f42-2bf5bafefac5.png)
![55 glasseffect](https://user-images.githubusercontent.com/5633645/39080247-86a53358-4500-11e8-86ce-235ed1cdde37.png)

![4 skyboxreflectionalbedo flat shaded opt 2](https://user-images.githubusercontent.com/5633645/39080454-4ec1a8ea-4505-11e8-8dde-41e7f737a136.gif)
![4 skyboxreflectionalbedo opt 2](https://user-images.githubusercontent.com/5633645/39080482-dcca4b56-4505-11e8-9ab5-81f847a054a3.gif)
![16 skyboxreflectionbump opt 2](https://user-images.githubusercontent.com/5633645/39080483-e79e9f5a-4505-11e8-8ff5-dcdea640bfdc.gif)
![20 hardrim opt](https://user-images.githubusercontent.com/5633645/39080416-7778dca0-4504-11e8-945a-c3b28fed17e8.gif)
![32 lightingtoon opt](https://user-images.githubusercontent.com/5633645/39080417-779b1acc-4504-11e8-8a86-e80da9ff38a1.gif)
![43 x-ray scanner improved opt 2](https://user-images.githubusercontent.com/5633645/39080493-20e79a46-4506-11e8-8492-9fcb87834e71.gif)
![44 1 windowedworldviewer opt 2](https://user-images.githubusercontent.com/5633645/39080507-595aaa6c-4506-11e8-8197-f35e7fb43f52.gif)
![56 waves opt](https://user-images.githubusercontent.com/5633645/39080418-7805f310-4504-11e8-8921-4c91b4e22a1a.gif)
![57 scrollingwaves opt](https://user-images.githubusercontent.com/5633645/39080419-7828f266-4504-11e8-828d-9f386e4b665b.gif)
![60 advancedhologram](https://user-images.githubusercontent.com/5633645/39101466-73684980-4670-11e8-9396-7b59856caad0.png)
![60 advancedhologram](https://user-images.githubusercontent.com/5633645/39142553-68f13a20-4701-11e8-93f0-75eaef91ef55.gif)

**Comment by marcioreyes** [comment]
Very nice shaders! Hope you can evolute more and more!

**Comment by matinas** [comment]
Thanks Marcio!
